title: locus-x64@pwn$
description: >- # this means to ignore newlines until "baseurl:"
  Exploring kernel exploitation.
author: Ali Raza
url: https://locus-x64.github.io
baseurl: ""

social:
  github: https://github.com/locus-x64
  twitter: https://twitter.com/locus_x64
  linkedin: https://www.linkedin.com/in/locus-x64
  email: mailto:elirazamumtaz@gmail.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

future: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can git be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/

#theme: jekyll-theme-architect

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
